"use client"
import React from 'react'
import Link from "next/link";
import useSWR from "swr";
import Api from "../../../lib/api";

const fetcher = async (url) => await Api.getApi(url);

export default function BlogsAndFaqSectionForGEO() {

    const { data: blogsApi, error: blogsApiError } = useSWR('/wp-json/wp/v2/posts?categories=181&per_page=4', fetcher);

    if (blogsApiError) return <div>No Data Found!</div>;

    return (
        <section className="bg-white blog-sec">
            <div className="container">
                <div className="row">

                    <div className="col-md-6">
                        <div className="blog">
                            <div className="title-mb">
                                <h2 className="element-subtitle">Blog</h2>
                                <h2 className="title">Latest From our blog</h2>
                            </div>
                            <div>
                                {
                                blogsApi && blogsApi.map((blog)=>(
                                    <div className="blogbox clearfix" key={blog.id}>
                                    <div className="image">
                                        {blog.featured_media_src_url && (
                                        <img src={blog.featured_media_src_url} alt="featured-image"/>
                                        )}
                                    </div>
                                    <div className="btext">
                                        <h4><Link href={blog.link} target="blank">{blog.title.rendered}</Link></h4>
                                        <div className="binfo">
                                        <span className="date"><i className="fi fi-ts-calendar-days"></i>{new Intl.DateTimeFormat('en-US', { year: 'numeric', month: 'long', day: 'numeric' }).format(new Date(blog.date))}</span>
                                        <span className="autour"><i className="fi fi-tr-comment-user"></i>Admin</span>
                                        </div>
                                    </div>
                                    </div>
                                ))
                                }
                            </div>
                        </div>
                    </div>

                    <div className="col-md-6">
                    <div className="faq">
                        <div className="title-mb">
                        <h2 className="element-subtitle">FAQS</h2>
                        <h2 className="title">frequently asked questions</h2>
                        </div>
                        <div>
                        <div id="accordionExample" className="accordion shadow">
                            <div className="card">
                            <div
                                id="headingOne"
                                className="card-header bg-white shadow-sm border-0"
                            >
                                <h6 className="mb-0 font-weight-bold">
                                <a
                                    href="#"
                                    data-toggle="collapse"
                                    data-target="#collapseOne"
                                    aria-expanded="true"
                                    aria-controls="collapseOne"
                                    className="d-block position-relative text-dark text-uppercase collapsible-link py-2"
                                >
                                    What is Generative Engine Optimization (GEO)?
                                </a>
                                </h6>
                            </div>
                            <div
                                id="collapseOne"
                                aria-labelledby="headingOne"
                                data-parent="#accordionExample"
                                className="collapse show"
                            >
                                <div className="card-body p-4">
                                <p className="m-0">
                                    GEO is the process of optimizing your website and content to appear in responses generated by AI-powered search engines like {`Google’s`} SGE (Search Generative Experience) and Bing Copilot.
                                </p>
                                </div>
                            </div>
                            </div>
                            <div className="card">
                            <div
                                id="headingTwo"
                                className="card-header bg-white shadow-sm border-0"
                            >
                                <h6 className="mb-0 font-weight-bold">
                                <a
                                    href="#"
                                    data-toggle="collapse"
                                    data-target="#collapseTwo"
                                    aria-expanded="false"
                                    aria-controls="collapseTwo"
                                    className="d-block position-relative collapsed text-dark text-uppercase collapsible-link py-2"
                                >
                                    How is GEO different from traditional SEO?
                                </a>
                                </h6>
                            </div>
                            <div
                                id="collapseTwo"
                                aria-labelledby="headingTwo"
                                data-parent="#accordionExample"
                                className="collapse"
                            >
                                <div className="card-body p-4">
                                <p className="font-weight-light m-0">
                                    While SEO focuses on ranking higher in search engine results, GEO ensures that your content is understood, summarized, and referenced accurately by generative AI systems that provide direct answers.
                                </p>
                                </div>
                            </div>
                            </div>
                            <div className="card">
                            <div
                                id="headingThree"
                                className="card-header bg-white shadow-sm border-0"
                            >
                                <h6 className="mb-0 font-weight-bold">
                                <a
                                    href="#"
                                    data-toggle="collapse"
                                    data-target="#collapseThree"
                                    aria-expanded="false"
                                    aria-controls="collapseThree"
                                    className="d-block position-relative collapsed text-dark text-uppercase collapsible-link py-2"
                                >
                                    Why should my business invest in GEO?
                                </a>
                                </h6>
                            </div>
                            <div
                                id="collapseThree"
                                aria-labelledby="headingThree"
                                data-parent="#accordionExample"
                                className="collapse"
                            >
                                <div className="card-body p-4">
                                <p className="font-weight-light m-0">
                                    As AI-driven search is rapidly changing how users discover information, GEO helps your brand stay visible in AI-generated responses, giving you an edge over competitors still relying solely on traditional SEO.
                                </p>
                                </div>
                            </div>
                            </div>
                            <div className="card">
                            <div
                                id="headingFour"
                                className="card-header bg-white shadow-sm border-0"
                            >
                                <h6 className="mb-0 font-weight-bold">
                                <a
                                    href="#"
                                    data-toggle="collapse"
                                    data-target="#collapseFour"
                                    aria-expanded="false"
                                    aria-controls="collapseFour"
                                    className="d-block position-relative text-dark text-uppercase collapsible-link py-2"
                                >
                                    What type of content benefits most from GEO?
                                </a>
                                </h6>
                            </div>
                            <div
                                id="collapseFour"
                                aria-labelledby="headingFour"
                                data-parent="#accordionExample"
                                className="collapse"
                            >
                                <div className="card-body p-4">
                                <p className="font-weight-light m-0">
                                    Educational, product-focused, and service-based content performs best with GEO, as these are commonly used in AI summaries, quick answers, and conversational search results.
                                </p>
                                </div>
                            </div>
                            </div>
                            <div className="card">
                            <div
                                id="headingFive"
                                className="card-header bg-white shadow-sm border-0"
                            >
                                <h6 className="mb-0 font-weight-bold">
                                <a
                                    href="#"
                                    data-toggle="collapse"
                                    data-target="#collapseFive"
                                    aria-expanded="false"
                                    aria-controls="collapseFive"
                                    className="d-block position-relative text-dark text-uppercase collapsible-link py-2"
                                >
                                    How do you measure success in GEO optimization?
                                </a>
                                </h6>
                            </div>
                            <div
                                id="collapseFive"
                                aria-labelledby="headingFive"
                                data-parent="#accordionExample"
                                className="collapse"
                            >
                                <div className="card-body p-4">
                                <p className="font-weight-light m-0">
                                    We track visibility in AI-generated search previews, analyze referral traffic from AI-driven engines, and monitor brand mentions and engagement in generative search interfaces.
                                </p>
                                </div>
                            </div>
                            </div>
                        </div>
                        </div>
                    </div>
                    </div>

                </div>
            </div>
        </section>
    )

}